### ISSUE TITLE
General Roadmap

### ISSUE THREAD

**Issue by justjanne** [justjanne/quassel#4]
Milestone 1: Usability
1. Working Builds
2. Websocket Support
3. Notifications
4. Web/Electron UI

Milestone 2: Cleanup
1. Split Quassel
2. Simplify project, remove unnecessary stuff

Milestone 3: Features
1. Editable/Deletable messages
2. Weechat Plugin
3. iOS Client

**Comment by TheOneRing** [comment]
Split Quassel -> Split core and ui in separate repositories
